name: Web

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Release Tag
        default: '1.1.1'
      environment:
        description: Environment to deploy
        required: true
        default: test
        type: choice
        options:
          - test
          - stg
          - prod

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: >-
        "${{ (github.event.inputs.environment == 'prod' && 'Web Production')
        || (github.event.inputs.environment == 'stg' && 'Web Staging')
        || (github.event.inputs.environment == 'test' && 'Web Testing') }}"
      url: >-
        "${{ (github.event.inputs.environment == 'prod' && 'https://prod.example.com')
        || (github.event.inputs.environment == 'stg' && 'https://stg.example.com')
        || (github.event.inputs.environment == 'test' && 'https://test.example.com') }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - if: github.event.inputs.environment == 'prod'
        run: echo "prod"

      - if: github.event.inputs.environment == 'stg'
        run: echo "stg"
